build: remove-from-known-hosts
	docker build -t {{container/name}} .

run: build
	docker run -p {{container/ssh-port}}:22 {{container/name}}

remove-from-known-hosts:
	ssh-keygen -R '[localhost]:{{container/ssh-port}}'

ssh-login:
	echo "Password is: cider"
	ssh root@localhost -p {{container/ssh-port}}

stop:
	docker stop `(docker ps --quiet --filter ancestor={{container/name}})` || exit 0

cleanup: stop
	docker remove `(docker ps --all --quiet --filter ancestor={{container/name}})`
